config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    member do
      post :favorite
      post :cancel
    end
    resources :reviews
  end

  namespace :account do
    resources :movies
    resources :reviews
  end
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews
  validates :filmname, presence: true
  has_many :movie_relationships
  has_many :members, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews
  has_many :movie_relationships
  has_many :participated_movies, :through => :movie_relationships, :source => :movie
  def is_member_of?(movie)
    participated_movies.include?(movie)
  end

  def favorite!(movie)
    participated_movies << movie
  end

  def cancel!(movie)
    participated_movies.delete(movie)
  end

end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!
  def index
    @movies = current_user.participated_movies
  end
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reviews = current_user.reviews
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  before_action :find_movie_and_check_permission, only: [:edit, :update, :destroy]
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.recent.paginate(:page => params[:page], :per_page => 5)
  end

  def edit
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if @movie.save
      current_user.favorite!(@movie)
      redirect_to movies_path
    else
      render :new
    end
  end

  def update
    if @movie.update(movie_params)
      redirect_to movies_path, notice: "编辑成功"
    else
      render :edit
    end
  end

  def destroy
    @movie.destroy
    flash[:alert] = "成功删除电影"
    redirect_to movies_path
  end

  def favorite
    @movie = Movie.find(params[:id])

    if !current_user.is_member_of?(@movie)
      current_user.favorite!(@movie)
      flash[:notice] = "收藏电影成功！"
    else
      flash[:warning] = "你之前已收藏过该电影！"
    end

    redirect_to movie_path(@movie)
  end

  def cancel
    @movie = Movie.find(params[:id])

    if current_user.is_member_of?(@movie)
      current_user.cancel!(@movie)
      flash[:alert] = "已取消收藏！"
    else
      flash[:warning] = "你还没有收藏过该电影，无法取消收藏！"
    end

    redirect_to movie_path(@movie)
  end

  private

  def find_movie_and_check_permission
    @movie = Movie.find(params[:id])

    if current_user != @movie.user
      redirect_to root_path, alert: "你没有编辑权限！"
    end
  end

  def movie_params
    params.require(:movie).permit(:filmname, :introduction)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create]
  before_action :check_permission, only: [:new, :create, :edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def edit
    @review = Review.find(params[:id])
    if current_user != @review.user
      redirect_to account_reviews_path, alert: "你没有编辑评论权限！"
    else
      render :edit
    end
  end

  def create
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  def update
    @review = Review.find(params[:id])
    if current_user != @review.user
      redirect_to account_reviews_path, alert: "你没有编辑评论权限！"
    end
    if @review.update(review_params)
      redirect_to account_reviews_path, alert: "编辑评论成功！"
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if current_user != @review.user
      redirect_to account_reviews_path, alert: "你没有删除评论权限！"
    else
      @review.destroy
      redirect_to account_reviews_path, alert: "删除评论成功！"
    end
  end


  private
  def check_permission
    @movie = Movie.find(params[:movie_id])
    if !current_user.is_member_of?(@movie)
      redirect_to movie_path(@movie), alert: "你还没有收藏电影，没有权限进行相应操作！"
    end
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "Welcome！"
  end
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def render_movie_introduction(movie)
    simple_format(movie.introduction)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 影评网
        <br>Design by 张伟
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">张伟影评网</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path) %> </li>
                <li><%= link_to("登录", new_user_session_path) %></li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_user.email %>
                        <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li> <%= link_to("我的电影", account_movies_path) %></li>
                    <li> <%= link_to("我的评论", account_reviews_path) %></li>
                    <li class="divider"> </li>
                    <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                  </ul>
                </li>
              <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Rails101</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/movies/_form.html.erb
<%= simple_form_for @movie do |f| %>
  <div class="form-group">
    <%= f.input :filmname, input_html: { class: "form-control"} %>
    <%= f.input :introduction, input_html: { class: "form-control"} %>
  </div>
  <%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/movies/_movie_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(movie.filmname, movie_path(movie)) %></td>
  <td><%= render_movie_introduction(movie) %></td>
  <td><%= movie.user.email %></td>
  <td>
    <% if current_user && current_user == movie.user %>
      <%= link_to("编辑", edit_movie_path(movie), class: "btn btn-sm btn-default")%>
      <%= link_to("删除", movie_path(movie),    class: "btn btn-sm btn-default",
                  method: :delete, data: { confirm: "Are you sure?" } )%>
    <% end %>
  </td>

</tr>

app/views/movies/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>编辑影片信息</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/movies/index.html.erb
<div class="col-md-12">
  <div class="movie">
    <%= link_to("添加新电影", new_movie_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>影片名</td>
        <td>影片简介</td>
        <td>发布者</td>
      </tr>
    </thead>
    <tbody>
      <%= render :partial => "movie_item", :collection => @movies, :as => :movie %>
    </tbody>
  </table>
</div>

app/views/movies/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增电影</h2>

    <hr>
    <%= render "form" %>

</div>

app/views/movies/show.html.erb
<div class="col-md-12">
  <div class="movie">
    <span class="pull-right">
      <% if current_user && current_user.is_member_of?(@movie) %>
        <label class="label label-success"> 已收藏电影 </label>
        <%= link_to("取消收藏", cancel_movie_path(@movie), method: :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning"> 未收藏电影 </label>
        <%= link_to("收藏电影", favorite_movie_path(@movie), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>
    <%= link_to("新增评论", new_movie_review_path(@movie), class: "btn btn-default pull-right")%>
    <% if current_user && current_user == @movie.user %>
      <%= link_to("编辑", edit_movie_path(@movie), class: "btn btn-primary pull-right")%>
    <% end %>
  </div>
  <h2><%= @movie.filmname %></h2>
  <p><%= @movie.introduction %></p>
  <table class="table">
    <thead>
     <tr>
        <th>评论内容</th>
        <th>发表者</th>
        <th>发表时间</th>
      </tr>
    </thead>
    <tbody>
      <% @reviews.each do |review| %>
        <tr>
          <td><%= review.content %></td>
          <td><%= review.user.email %></td>
          <td><%= review.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center">
    <%= will_paginate @reviews %>
  </div>
</div>

app/views/reviews/edit.html.erb
<h2 class="text-center">编辑评论</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@movie,@review] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "Submit", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h2 class="text-center">新增评论</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@movie,@review] do |f| %>
    <div class="form-group">
      <%= f.input :content, input_html: { class: "form-control"} %>
    </div>
    <div class="form-actions">
      <%= f.submit "提交", disable_with: "Submiting...", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1> 欢迎来到影评网 </h1>